name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/**

jobs:
  build:
    name: "cs2-modsharp-egg"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/prefix/cs2-modsharp-egg:latest
            ghcr.io/prefix/cs2-modsharp-egg:${{ github.sha }}
